project:
  type: website
  output-dir: docs
  preview: 
    port: 4200

website:
  title: "bggj"
  site-url: "https://www.bggj.is"
  description: Blogg um tölfræði og gögn
  search: false
  
  repo-url: https://github.com/bgautijonsson/bgautijonsson.github.io
  
  favicon: favicon.ico
  
  google-analytics: "G-EGQ9KVCY2C"
  open-graph: true
  twitter-card: 
    creator: "@bggjonsson"
    card-style: summary_large_image
    site: "@bggjonsson"
    
  navbar: 
    left:
      - text: "blog"
        href: index.qmd
      - text: "about"
        href: about.qmd
        
    right:
      - icon: twitter
        href: https://twitter.com/bggjonsson
      - icon: github
        href: https://github.com/bgautijonsson/bgautijonsson.github.io
  
  sidebar:
    - title: blog
    - title: about
        
format:
  html:
    theme: [flatly, theme.scss]
    code-fold: true
    title-block-banner: true
    citation-location: margin
    highlight-style: atom-one
    code-overflow: scroll
    execute:
      freeze: auto
      warning: false
      message: false



editor: source
