---
title: "About my PhD"
---

# Introduction

I'm developing and maintaining this part of my page to go along with my PhD studies for reproducibility and to held me keep my sanity intact for the next years.

The main gist of my PhD research will be adding to the `Max-and-Smooth` method previously developed and published by my advisor, Birgir Hrafnkelsson, and others [here](https://arxiv.org/abs/1907.11969){target="_blank"}

# Other materials

## R package on Github

I've put the code and data for any modeling into an R package, `bggjphd`, which I keep up to date [on Github](https://github.com/bgautijonsson/bggjphd)

## Docker Container


For reproducibility I keep a [Docker container on Docker Hub](https://hub.docker.com/r/bgautijonsson/phdocker) that sets up an R environment and all the packages needed to run code from the `bggjphd` package.

# Summary of my work thus far

## Data

### UKCP

[UKCP Data](articles/methods/data/ukcp/index.qmd)

Gather data on hourly precipitation 

## Models

### Maximum Likelihood Estimation 

### Spatial Smoothing of MLEs 